# Generated by Django 3.2 on 2023-05-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230507_2302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
